{% set version = "0.5.0" %}

package:
  name: django-uuidfield
  version: {{ version }}

source:
  url: https://github.com/dcramer/django-uuidfield/archive/{{ version }}.tar.gz
  sha256: 8461004b66871edc04435cba608519c5f587b66a830ee8646df83edae40a9c99

build:
  number: 1
  script: python -m pip install -vv .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.7,<1.8

test:
  imports:
    - uuidfield

about:
  home: https://github.com/dcramer/django-uuidfield
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'UUIDField in Django'

extra:
  recipe-maintainers:
    - ocefpaf
