travis:
  secure:
    BINSTAR_TOKEN: LDD5B27lyx9wiCIJixIhmZa+5YxtesAcFwSKqq2YUKIvWqz4ZSJdW5QEljaKvDcwHxBy90kV1HgByCIhAiIUaWgrVwMIDI6G/JwRSSKqXmIATo9+VOjAMm7eWwoyi35U4z+6UHddPnFDG5ONHQsEXIKZnaQdEoQ5ssj52naQ+NOkNPBsRVDOXxplrf8dZGgQDtF3IPSIOaCuB5ZI3ap2SPiZiV+Ws6q4LZbG1+31qDsd0f2afpcAgmZPBXy6OB69Vwzx37B3CQLXf+24aw1lfZYlnp19xpwVoTshNB3+xoTnYe4zW/APB8kBruuVNPojryviFgO9CfLHrM81Wd55UOjDgQB0DRZ2ZSryPu5DH5ebR4xorX70JzHf0/KUCEDm1guMA0bfTfcsj2HFPK8D74kphlgoj6E3FFRVBsLqnrhyj6qzhvDrR8ES0HX7mnraTSl63YHccu7EfnPPNGAkMlQoe64DPSN0Wp5CsL0JfM/1IFQhvGOw1xe/k4DYB4p+Ce+PAJy+eL8209+ug6DEdWLDzfqKZ1WmuWRwpClrpWmGM+mABovIXrFoQAS7oq5nFjTsjH+r//bPcFdWIsfmxEFsyXSHtJomF1dy0GKd0JBOrbbM6ph1XaQ8SibieCPIRu5ebYLuap1uXnnnJHTHXMdXjUqS2mjO70uLDXTvYEc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
