travis:
  secure:
    BINSTAR_TOKEN: co1hDr3YkJZUtehrd26dCWT4GfjwvloJ1OUd+Hp8aS69Zn7wVHAEHRed/6Q5dG6KT7udV03cQ7pn+iVAIx/8HgEuDVnw835HTSQ0RyYzvYBS8jfdFRn48/UkVsvqrM994/8S6AWfkeJ12GsxU4bxKl7ihpDZJzc8ARWvmjDI2wL3ZivBINqVFDadluQzDxSbQi93++GA4yk/UKj/oAlpO0aai062A7oBrMda0ltS0Bax+6VTybC5UjyRz0OCH/EbhJkYILfRgwr3881SL6bkrqrnPINnq8C1CUBow2Q0dsp5Qgiv48Fm0N9/+qx3jboz1UmkH1EzrpPb6uV4r1qc2XWE1TP9gAia2bev4FRDtUoe225UH8MHiFS84IarHXl9RwLIcY33EBgd7/LmYGTeDd9wCzFzHGBWCvWMKoq5RwlEyFa0qZzMV2XRIZJr8Z/2NR0g6wvc92eArqN1uwqe3Qs9jvSOONbmevetcr4Zo7nR9pMV+7m0IUEkta06y4cJ2jp/fOR1VnHXNzL1WpCkRXZUC4ZpgaFiWBvz+b7FHGKXsVIV0TKIBBGId33LHRCeZJta8gZ7Xm0MVKsfW1ZI+pRNCkJHRXgkM+h5MzePpOyTaIdG1kh3uDynwiRo0fYCWwRHHAW3BkpLifeuOKBFrZJWsIlx1GA9gDhaBPR2qd4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
